import { BankAccount, Transaction } from "@/lib/types";
import {
  Utensils,
  Car,
  Briefcase,
  Film,
  HeartHandshake,
  ShoppingBag,
  Building2,
  CreditCard,
  Landmark,
  Smartphone,
} from "lucide-react";

export const allTransactions: Transaction[] = [
  {
    id: 5,
    date: "2025-09-07",
    description: "Salary Credit",
    category: "Income",
    amount: 50000,
    type: "inflow",
    icon: Briefcase,
  },
  {
    id: 3,
    date: "2025-09-09",
    description: "Freelance Payment",
    category: "Income",
    amount: 15000,
    type: "inflow",
    icon: Briefcase,
  },
  {
    id: 7,
    date: "2025-09-05",
    description: "Mom",
    category: "Family",
    amount: 1000,
    type: "inflow",
    icon: HeartHandshake,
  },
  {
    id: 1,
    date: "2025-09-10",
    description: "Zomato Order",
    category: "Food",
    amount: -450,
    type: "outflow",
    icon: Utensils,
  },
  {
    id: 2,
    date: "2025-09-10",
    description: "Uber Ride",
    category: "Travel",
    amount: -280,
    type: "outflow",
    icon: Car,
  },
  {
    id: 4,
    date: "2025-09-08",
    description: "Netflix Subscription",
    category: "Entertainment",
    amount: -649,
    type: "outflow",
    icon: Film,
  },
  {
    id: 6,
    date: "2025-09-06",
    description: "Amazon Purchase",
    category: "Shopping",
    amount: -2500,
    type: "outflow",
    icon: ShoppingBag,
  },
  {
    id: 8,
    date: "2025-09-04",
    description: "Spotify",
    category: "Entertainment",
    amount: -119,
    type: "outflow",
    icon: Film,
  },
];

export const allBankAccounts: BankAccount[] = [
  {
    name: "STATE BANK OF INDIA",
    balance: "₹27,932",
    accountNumber: "34536896452",
    ifscCode: "SBIN0006586",
    swiftBic: "SBININBBXXX",
    holderName: "NISHANT VERMA",
    icon: Building2,
  },
  {
    name: "HDFC BANK",
    balance: "₹2,58,630",
    accountNumber: "92536896452",
    ifscCode: "HDFCINBBXXX",
    swiftBic: "HDFCINBB",
    holderName: "NISHANT VERMA",
    icon: CreditCard,
  },
  {
    name: "ICICI BANK",
    balance: "₹74,932",
    accountNumber: "12345678901",
    ifscCode: "ICICINBBXXX",
    swiftBic: "ICICINBB",
    holderName: "NISHANT VERMA",
    icon: Landmark,
  },
  {
    name: "AXIS BANK",
    balance: "₹65,310",
    accountNumber: "98765432109",
    ifscCode: "UTIBINBBXXX",
    swiftBic: "AXISINBB",
    holderName: "NISHANT VERMA",
    icon: Smartphone,
  },
];

export const categories = [
  "All",
  "Food",
  "Travel",
  "Income",
  "Entertainment",
  "Shopping",
  "Family",
];
