import {
  Utensils,
  Car,
  Briefcase,
  Film,
  HeartHandshake,
  ShoppingBag,
} from "lucide-react";

export const allTransactions = [
  {
    id: 1,
    date: "2025-09-10",
    description: "Zomato Order",
    category: "Food",
    amount: -450,
    type: "outflow",
    icon: Utensils,
  },
  {
    id: 2,
    date: "2025-09-10",
    description: "Uber Ride",
    category: "Travel",
    amount: -280,
    type: "outflow",
    icon: Car,
  },
  {
    id: 3,
    date: "2025-09-09",
    description: "Freelance Payment",
    category: "Income",
    amount: 15000,
    type: "inflow",
    icon: Briefcase,
  },
  {
    id: 4,
    date: "2025-09-08",
    description: "Netflix Subscription",
    category: "Entertainment",
    amount: -649,
    type: "outflow",
    icon: Film,
  },
  {
    id: 5,
    date: "2025-09-07",
    description: "Salary Credit",
    category: "Income",
    amount: 50000,
    type: "inflow",
    icon: Briefcase,
  },
  {
    id: 6,
    date: "2025-09-06",
    description: "Amazon Purchase",
    category: "Shopping",
    amount: -2500,
    type: "outflow",
    icon: ShoppingBag,
  },
  {
    id: 7,
    date: "2025-09-05",
    description: "Mom",
    category: "Family",
    amount: 1000,
    type: "inflow",
    icon: HeartHandshake,
  },
  {
    id: 8,
    date: "2025-09-04",
    description: "Spotify",
    category: "Entertainment",
    amount: -119,
    type: "outflow",
    icon: Film,
  },
];

export const categories = [
  "All",
  "Food",
  "Travel",
  "Income",
  "Entertainment",
  "Shopping",
  "Family",
];
